/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasiRouteImport } from './routes/casi'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FontiRouteImport } from './routes/fonti'
import { Route as IntervisteRouteImport } from './routes/interviste'
import { Route as LabRouteImport } from './routes/lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasiRoute = CasiRouteImport.update({
  id: '/casi',
  path: '/casi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FontiRoute = FontiRouteImport.update({
  id: '/fonti',
  path: '/fonti',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervisteRoute = IntervisteRouteImport.update({
  id: '/interviste',
  path: '/interviste',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casi': typeof CasiRoute
  '/dashboard': typeof DashboardRoute
  '/fonti': typeof FontiRoute
  '/interviste': typeof IntervisteRoute
  '/lab': typeof LabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casi': typeof CasiRoute
  '/dashboard': typeof DashboardRoute
  '/fonti': typeof FontiRoute
  '/interviste': typeof IntervisteRoute
  '/lab': typeof LabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casi': typeof CasiRoute
  '/dashboard': typeof DashboardRoute
  '/fonti': typeof FontiRoute
  '/interviste': typeof IntervisteRoute
  '/lab': typeof LabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/casi' | '/dashboard' | '/fonti' | '/interviste' | '/lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/casi' | '/dashboard' | '/fonti' | '/interviste' | '/lab'
  id:
    | '__root__'
    | '/'
    | '/casi'
    | '/dashboard'
    | '/fonti'
    | '/interviste'
    | '/lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasiRoute: typeof CasiRoute
  DashboardRoute: typeof DashboardRoute
  FontiRoute: typeof FontiRoute
  IntervisteRoute: typeof IntervisteRoute
  LabRoute: typeof LabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casi': {
      id: '/casi'
      path: '/casi'
      fullPath: '/casi'
      preLoaderRoute: typeof CasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonti': {
      id: '/fonti'
      path: '/fonti'
      fullPath: '/fonti'
      preLoaderRoute: typeof FontiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviste': {
      id: '/interviste'
      path: '/interviste'
      fullPath: '/interviste'
      preLoaderRoute: typeof IntervisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasiRoute: CasiRoute,
  DashboardRoute: DashboardRoute,
  FontiRoute: FontiRoute,
  IntervisteRoute: IntervisteRoute,
  LabRoute: LabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
